---
- name : node ppa key is added
  apt_key: url='https://deb.nodesource.com/gpgkey/nodesource.gpg.key' state=present

- name: node ppa is available
  apt_repository: repo='deb https://deb.nodesource.com/node_0.12 trusty main' update_cache=yes

- name: nodejs is installed
  apt: name=nodejs state=latest

- name: Interactive Activities daemon is configured
  template: src=upstart.conf dest=/etc/init/interactive-activities.conf backup=no

- name: code is synchronized via git to temp directory
  git: dest={{app_base_path}}.tmp repo={{git_repo}} version={{commit}}
  when: env != 'development'

- name: npm install has been run
  npm: path={{app_base_path}}.tmp

- name: production version of the application has been built
  command: npm run build
  args:
    chdir: "{{ app_base_path }}.tmp"

- name: current production build is removed
  command: rm -rf {{app_base_path}}

- name: new production build is in place
  command: mv {{app_base_path}}.tmp {{app_base_path}}

- name: the service is restarted
  service: name=interactive-activities state=restarted
