---
- name: update the apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: upgrade all packages safely
  apt: upgrade=safe
  when: env != "development"

- name: Create "deployer" user
  user: name={{ deploy_user }}

- name: Disable password requirement for the "deployer" user to use sudo
  lineinfile:
    dest=/etc/sudoers
    state=present
    line="{{ deploy_user }} ALL=(ALL) NOPASSWD:ALL"
    validate="visudo -cf %s"

- name: Whitelist users for SSH access
  lineinfile:
    dest=/etc/ssh/sshd_config
    state=present
    regexp="^AllowUsers\s"
    line="AllowUsers {{ deploy_user }}"

- name: disallow password authentication
  lineinfile:
    dest=/etc/ssh/sshd_config
    state=present
    regexp="^PasswordAuthentication"
    line="PasswordAuthentication no"
  notify: restart sshd

- name: disallow challenge response authentication
  lineinfile:
    dest=/etc/ssh/sshd_config
    state=present
    regexp="^ChallengeResponseAuthentication"
    line="ChallengeResponseAuthentication no"
  notify: restart sshd

- name: install unattended upgrades
  apt: name=unattended-upgrades state=present

- name: configure unattended upgrades
  copy: src=10periodic dest=/etc/apt/apt.conf.d/
