---
- hosts: all
  gather_facts: false
  remote_user: root
  tasks:
    - name: Create admin user
      user: name={{ admin_user }}

    - name: Disable password requirement for the webhook user to use sudo
      lineinfile:
        dest=/etc/sudoers
        state=present
        line="{{ admin_user }} ALL=(ALL) NOPASSWD:ALL"
        validate="visudo -cf %s"
    - name: Whitelist users for SSH access
      lineinfile:
        dest=/etc/ssh/sshd_config
        state=present
        regexp="^AllowUsers\s"
        line="AllowUsers {{ admin_user }}"
